-- total_cost-Показатель-Исходные данные
-- revenue-Показатель-Исходные данные
-- purchases_count-Показатель-Исходные данные
-- visitors_count-Показатель-Исходные данные
-- CPU-Показатель-[total_cost] / [visitors_count]
-- CPL-Показатель-[total_cost] / [leads_count]
-- CPPU-Показатель-[total_cost] / [purchases_count]
-- ROI, %-Показатель-([revenue] - [total_cost]) / [total_cost] * 100
-- Конверсия в лид (%)-Показатель-[leads_count] / [visitors_count] * 100
-- Конверсия в покупку (%)-Показатель-[purchases_count] / [leads_count] * 100
-- Прибыль-Показатель-[revenue] - [total_cost]
-- Средний чек-Показатель-[revenue] / [purchases_count]
